### ISSUE TITLE
Backwards compatibility

### ISSUE THREAD

**Issue by mathiasbynens** [gibson042/ecma262-proposal-well-formed-stringify#2]
https://github.com/gibson042/ecma262-proposal-well-formed-stringify#backwards-compatibility states this change is backwards compatible. That’s only true if we assume `JSON.stringify` output only ever gets consumed by spec-compliant `JSON.parse` implementations or userland alternatives.

I wouldn’t be surprised if this change ends up breaking something. I’d suggest rephrasing the FAQ section to state as much. Let’s explicitly acknowledge that we’ll really only know if/when a browser tries to ship it.

**Comment by jridgewell** [comment]
Man, you beat me to this. I was on my phone and it was too much typing.

> Let’s explicitly acknowledge that we’ll really only know if/when a browser tries to ship it.

It's unfortunately not at all backwards compatible. AMP's codebase will break due to this, and I'm sure hundreds of others. It's _very_ common to assert the `JSON.stringify` output is equal to some string, as hacky deep equality equals. Anything that uses a surrogate pair will then be broken.

```js
const obj = {
  example: "test💩"
};

assert.equals(JSON.stringify(obj), `{"example":"test💩"}`);

We _might_ be able to get away with encoding lone surrogates (I don't think I've ever created one on purpose). But paired will definitely cause problems.

**Comment by mathiasbynens** [comment]
Hmm… I’m worried mostly about production code, and am not terribly concerned about test suites (especially if they use hacks like the above, and even less so when they’re actively maintained).

Options:

1. In its current version, the proposal escapes every single surrogate, regardless of whether it’s a lone surrogate or part of a surrogate pair.
1. We could [extend this to escape every symbol that is not printable ASCII](https://esdiscuss.org/topic/code-points-vs-unicode-scalar-values#content-17). This would make `JSON.stringify`’s output ASCII-safe.
1. We could be more conservative and only escape lone surrogates. This would complicate the spec slightly, as we’d need to peek at the next code unit for every high surrogate.

**Comment by gibson042** [comment]
Oops, it was a mistake on my part. The intent is to replace only _unpaired_ surrogates with escape sequences. Will fix shortly.
