### ISSUE TITLE
One parser potentially would not handle escaped lone surrogates

### ISSUE THREAD

**Issue by apaprocki** [gibson042/ecma262-proposal-well-formed-stringify#5]
Looks like this would return a parse error?

https://github.com/nlohmann/json/blob/develop/single_include/nlohmann/json.hpp#L2321-L2359

**Comment by gibson042** [comment]
Yes, as it is allowed to do. That parser already rejects unescaped lone surrogates, too: https://github.com/nlohmann/json/blob/develop/single_include/nlohmann/json.hpp#L2666-L2671

**Comment by apaprocki** [comment]
Ok, just wanted to check it. Thanks

**Comment by mathiasbynens** [comment]
Thanks for bringing it up! Always better to double-check.
